openapi: 3.0.3
info:
  title: Broken API
  version: 1.0.0
paths:
  /broken:
    get:
      summary: broken yaml below
      responses:
        '200':
          description: ok
    post
      summary: invalid because colon is missing
