openapi: 3.0.3
info:
  title: Demo Orders API
  version: 1.0.0
paths:
  /Orders:
    get:
      summary: Get all orders
      responses:
        '200':
          description: success
    post:
      summary: Create order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: created
  /orders/{orderId}:
    get:
      summary: Get order by id
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: success
